SET NAMES utf8;

UPDATE `creature_ai_texts` SET `content_loc2` = 'TU VEUX BOIRE ? ON A À BOIRE !' WHERE `entry` = -719;
UPDATE `creature_ai_texts` SET `content_loc2` = 'HEY TOI ! BOIS BREUVAGE OGRE ! RENDS-TOI GRAND ET FORT !' WHERE `entry` = -718;
UPDATE `creature_ai_texts` SET `content_loc2` = 'VOUS ESSAYEZ LA MEILLEURE, MAINTENANT ESSAYEZ LE RESTE ! BREUVAGE OGRE !' WHERE `entry` = -717;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Préparez-vous pour une éternité d\'angoisse et de torture - la vengeance sera mienne...' WHERE `entry` = -716;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Affrontez mon champion, mortels !' WHERE `entry` = -715;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Laissez les flammes du chaos vous engloutir !' WHERE `entry` = -714;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ilifar, votre maître vous appelle !' WHERE `entry` = -713;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Moi, va te découper et te manger !' WHERE `entry` = -712;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Cadavre fait boum !' WHERE `entry` = -711;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Aaaargh...' WHERE `entry` = -710;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Trop faim ! Doit manger !' WHERE `entry` = -709;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Plus tuer, plus sang, plus MANGER !' WHERE `entry` = -708;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s se transforme en mammouth !' WHERE `entry` = -707;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s amorce sa transformation !' WHERE `entry` = -706;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s commence à trembler !' WHERE `entry` = -705;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Si nos dieux ils peuvent mourir... Alors nous aussi...' WHERE `entry` = -704;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Plus si fort maintenant.' WHERE `entry` = -703;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Qui c\'est qui va m\'arrêter, toi ?' WHERE `entry` = -702;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je les écrase les cafards comme vous !' WHERE `entry` = -701;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le sol il va vous avaler d\'un coup !' WHERE `entry` = -700;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Préparez-vous à kek\'chose de bien... plus... GRAND !' WHERE `entry` = -699;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le Fléau on l\'a repoussé. Tu crois que VOUS, vous avez une chance ?' WHERE `entry` = -698;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s demande un raptor !' WHERE `entry` = -697;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s dresse ses serres de façon menaçante !' WHERE `entry` = -696;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Argghh !! Tharon\'ja en aura davantage !' WHERE `entry` = -695;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Non ! Un aperçu... bien trop bref !' WHERE `entry` = -694;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tharon\'ja peut utiliser votre dépouille mortelle !' WHERE `entry` = -693;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Votre chair est maintenant au service de Tharon\'ja !' WHERE `entry` = -692;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Comme c\'était écrit !' WHERE `entry` = -691;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Comme Tharon\'ja l\'avait prédit.' WHERE `entry` = -690;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Im... Impossible ! Tharon’ja est éternel ! Tharon’ja... est...' WHERE `entry` = -689;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tharon\'ja voit tout ! Les efforts des mortels ne mettront pas fin à la dynastie éternelle !' WHERE `entry` = -688;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Qui ose abattre un des commandants de Kargath ? Vous allez payer pour ça... par votre chair !' WHERE `entry` = -687;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s commence à incanter des soins massifs !' WHERE `entry` = -686;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Qu\'est ce que c\'est que ça ? Vos parents ne vous ont rien appris ?' WHERE `entry` = -685;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous, retournez au travail !' WHERE `entry` = -684;
UPDATE `creature_ai_texts` SET `content_loc2` = 'C\'est terrible… À force de vous cogner dessus, bande de péons flemmards, j\'en ai mal aux bras !' WHERE `entry` = -683;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Hep ! Vous, là-bas ! Oui, par ici… Je suis dans cette cage !' WHERE `entry` = -682;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Trop tôt ! Vous vous êtes relâché trop tôt !' WHERE `entry` = -681;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Debout ! On se lève et on retourne au travail !' WHERE `entry` = -680;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Allez, on se grouille ! Plus vous mettrez longtemps, plus je vous ferai mal !' WHERE `entry` = -679;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Esclaves, aidez-moi !' WHERE `entry` = -678;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La souffrance ne s\'arrêtera jamais ?' WHERE `entry` = -677;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Aidez-moi ! Aidez-moi, par pitié !' WHERE `entry` = -676;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Comment pouvez-vous me laisser ici ?' WHERE `entry` = -675;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Pour Kargath ! Pour la Victoire !' WHERE `entry` = -674;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous là ! Garder un oeil sur ces remparts, des intrus peuvent approcher à tout moment !' WHERE `entry` = -673;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ce monde nous APPARTIENT !' WHERE `entry` = -672;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Imbéciles incompétents ! Auchindoun aurait dû être à nous ! Regardez-vous, à cavaler comme des rats !' WHERE `entry` = -671;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La douce voix d\'Anaya disparaît dans la brume, "Sache que je t\'aimerai toujours..."' WHERE `entry` = -670;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Adieu, Cerellean, jusqu\'à ce que nous soyons réunis à nouveau...' WHERE `entry` = -669;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Malheureusement, tout cela est bientôt fini... Les attaches qui me lient à ce monde s\'affaiblissent, et m\'entrainent au loin...' WHERE `entry` = -668;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ne laisse pas le doute troubler ton coeur, bien-aimée. Tu dois me libérer de l\'esclavage, et pour cela, je t\'aime d\'autant plus.' WHERE `entry` = -667;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Les siècles ont été cruels envers toi et moi, mon amour, mais sois-en assuré, nous sommes finalement réunis.' WHERE `entry` = -666;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Comment, mon amour ? Comment vais-je trouver la force de faire face aux époques de ce monde sans toi à mes côtés...' WHERE `entry` = -665;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Non ! Anaya... Anaya ! Ne me laisse pas ! S\'il te plaît...' WHERE `entry` = -664;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tu me détestes, mon amour ? J\'ai été forcé de détruire ton enveloppe charnelle, pour que ton esprit soit libéré d\'une malheureuse servitude.' WHERE `entry` = -663;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ce doît être un destin bien cruel que de nous permettre ceci après mille ans d\'absence...' WHERE `entry` = -662;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Anaya...? Est-ce que mes yeux me trompent ? Est-ce vraiment toi ?' WHERE `entry` = -661;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Qu\'est-ce... que c\'est ? Serait-ce la réponse à mes prières ? Elune m\'a accordé une arme - cette faux - pour vaincre les démons.' WHERE `entry` = -660;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Déesse, accorde-moi le pouvoir de vaincre mes ennemis ! Ecoute-moi, s\'il te plaît, mon besoin est désespéré et ma cause est juste !' WHERE `entry` = -659;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le nombre de mes compagnons se réduit, déesse, et mon propre pouvoir sera bientôt insuffisant pour retenir les démons de Gangrebois.' WHERE `entry` = -658;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous n\'obtiendrez rien jusqu\'à ce que vous ayez parlé, misérable !' WHERE `entry` = -657;
UPDATE `creature_ai_texts` SET `content_loc2` = 'S\'il vous plaît ! Je dois bientôt me nourrir de quelque chose... Un cristal de mana... un éclat... n\'importe quoi ! La douleur est insupportable !' WHERE `entry` = -656;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Dites le nous ! Où se cache votre chef ?' WHERE `entry` = -655;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Snivvle est ici ! Snivvle prend la mine de Froide-dent !' WHERE `entry` = -654;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ahhh... ARRRGH ! Je ne pensais pas... être un jour libéré de son emprise....' WHERE `entry` = -653;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Venez à moi, mes frères ! Venez dévorer leurs chairs !' WHERE `entry` = -652;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Auum na-l ak-k-k-k, isshhh.' WHERE `entry` = -651;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Bientôt, vous entendrez la voix du Maître.' WHERE `entry` = -650;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous avez fait votre choix.' WHERE `entry` = -649;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous allez faire l\'expérience de mon tourment !' WHERE `entry` = -648;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La pestilence soit sur vous !' WHERE `entry` = -647;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Uunak-hissss tik-k-k-k-k !' WHERE `entry` = -646;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vos armures sont inutiles contre mes nuées !' WHERE `entry` = -645;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Une agonie éternelle vous attend !' WHERE `entry` = -644;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je devrais être reconnaissant... Mais ça fait longtemps que j\'en suis incapable...' WHERE `entry` = -643;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je sens des vivants. Soyez prêts.' WHERE `entry` = -642;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J\'entends des pas. Soyez sur vos gardes.' WHERE `entry` = -641;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Gardez un oeil sur le tunnel. Personne ne doit le traverser !' WHERE `entry` = -640;
UPDATE `creature_ai_texts` SET `content_loc2` = 'C\'était stupide de venir.' WHERE `entry` = -639;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Hash\'tak hi\'tak.' WHERE `entry` = -638;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Comme l\'ordonne Anub\'Arak !' WHERE `entry` = -637;
UPDATE `creature_ai_texts` SET `content_loc2` = 'À table, mes petits !' WHERE `entry` = -636;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ils ont faim...' WHERE `entry` = -635;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ce royaume appartient au Fléau. Seuls les morts peuvent y pénétrer !' WHERE `entry` = -634;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ohh...' WHERE `entry` = -633;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Notre tâche n\'est pas encore terminée !' WHERE `entry` = -632;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Qu\'est ce que c\'est ? Mag thorin Kar ! Tuez-les !' WHERE `entry` = -631;
UPDATE `creature_ai_texts` SET `content_loc2` = 'C\'est tout ce que vous... pouvez ?' WHERE `entry` = -630;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Enfin on avance un peu !' WHERE `entry` = -629;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Quoi ? Mais où diable...? Ne restez pas les bras croisés TUEZ QUELQU\'UN !' WHERE `entry` = -628;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Alors apprenez-moi Kel\'Thuzad. Apprenez-moi tout ce que vous savez...' WHERE `entry` = -627;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Et le Kirin Tor ? Qu\'est-ce qu\'ils ont à dire de la nécromancie ?' WHERE `entry` = -626;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Alors vous pouvez m\'apprendre ceci... cela...' WHERE `entry` = -625;
UPDATE `creature_ai_texts` SET `content_loc2` = 'En temps voulu, Helcular... Tout en temps voulu...' WHERE `entry` = -624;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mais pour être parfaitement franc, je me fiche de ce que le Kirin Tor peut penser ! Ils sont fous, avec leurs méthodes archaïques.' WHERE `entry` = -623;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ce n\'est pas quelque chose qui vous concerne, Helcular, comme ça ne concerne ni le Kirin Tor ni les nécromanciens.' WHERE `entry` = -622;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nécromancie. Ça s\'appelle la nécromancie. Et oui, j\'ai le pouvoir de vous bénir avec ce cadeau.' WHERE `entry` = -621;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ne faîtes pas de bruit, Helcular. Les étrangers sont en nombre...' WHERE `entry` = -620;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Qu\'est ce que tu mets dans ta pipe Nat ?' WHERE `entry` = -619;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ça n\'arrivera jamais, Nat.' WHERE `entry` = -618;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Pas question !' WHERE `entry` = -617;
UPDATE `creature_ai_texts` SET `content_loc2` = 'C\'est fou n\'est ce pas ?' WHERE `entry` = -616;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Il finit par détruire entièrement le fort, par libérer tous les orcs qui étaient captif dans le camp et par accéder au pouvoir en temps que roi des orcs... Chef de guerre ou quelque chose.' WHERE `entry` = -615;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Celui où je suis dans le Fort-de-Durn, et que l\'un de ces orcs que Landenoire garde comme esclave personnel s\'évade...' WHERE `entry` = -614;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Comme si ce n\'était pas assez fou, ils ont décidé de quitter le business de la glace pour devenir des aventuriers... Ils ont voyagé à travers le monde et ont finalement disparu à travers un portail. Je me suis réveillé avec des sueurs froides après que l\'un...' WHERE `entry` = -613;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Eh bien dans ce rêve, ils finissent par inventer quelque chose appelé "la crème glacée", qu\'ils aromatisent avec des fraises... Eh bien, une longue histoire courte où ils finissent par se retrouver riche !' WHERE `entry` = -612;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je ne peux même pas croire celui-là... Vous connaissez ces deux grands escrocs de Foror et Tigule ?' WHERE `entry` = -611;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Eh bien, il retourne vers le roi en prétendant que tout va bien, tire son épée, et court vers le roi... bien, vous savez... le tue sur place...' WHERE `entry` = -610;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mais malheureusement, Arthas est consumé par le mal et il devient le mal lui-même...' WHERE `entry` = -609;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Celui-là est vraiment sombre... Le fils du roi, Arthas... Eh bien, il va combattre les ténèbres, avec Uther. *Nat se frappe le front*' WHERE `entry` = -608;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je suis un peu comme le dieu de la pêche...' WHERE `entry` = -607;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Et des gens du monde entier viennent me rendre hommage... et apprendre à pêcher.' WHERE `entry` = -606;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Dans ce rêve, j\'étais un maître mondial de la pêche. J\'ai déménagé dans un endroit appelé Kalimdor...' WHERE `entry` = -605;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Et comme si ce n\'était pas assez fou, ce grand démon est tué par une bande de lumières flottantes... Oh, je suis aussi une femme elfe dans celui là... Yep...' WHERE `entry` = -604;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Sorti de nulle part, un démon, ou quelque chose de 300 pieds de haut, grimpe et commence l\'escalade de l\'arbre...' WHERE `entry` = -603;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je suis donc sur la montagne avec quelques vieux arbres. Une bande d\'elfes courant de partout...' WHERE `entry` = -602;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nat, j\'ai entendu quelques gros mensonges dans ma vie, mais celui-là c\'est la cerise sur le gâteau.' WHERE `entry` = -601;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Parfois, quand je suis éveillé, je pense qu\'ils nous observent. Peut-être ils nous observent maintenant...' WHERE `entry` = -600;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous sommes comme leurs marionnettes - nous dansons, pleurons, combattons et disons des bétises pour les divertir.' WHERE `entry` = -599;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Celui où des centaines de personnes nous observent depuis le ciel...' WHERE `entry` = -598;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Impossible !' WHERE `entry` = -597;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Peux-tu imaginer une chose pareille, Hal ? Tu le peux ?' WHERE `entry` = -596;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Moulin-de-Tarren est détruit par une force incontrôlable de morts-vivants et devient de plus en plus ennemi avec Austrivage.' WHERE `entry` = -595;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ce même rêve... Le rêve insensé. Tu te souviens ?' WHERE `entry` = -594;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Lequel ?' WHERE `entry` = -593;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J\'ai encore fait ce rêve la nuit dernière...' WHERE `entry` = -592;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Oui, Nat ?' WHERE `entry` = -591;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Hal...' WHERE `entry` = -590;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je ne me sens pas… très bien.' WHERE `entry` = -589;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Quand est-ce qu\'on mange ?' WHERE `entry` = -588;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Kibler fait l\'objet d\'une enquête du G.E.T.A.' WHERE `entry` = -587;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Opus veut l\'or de Cuergo...' WHERE `entry` = -586;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ils vont tous au Pic mais ne reviennent jamais... tout comme Bijou.' WHERE `entry` = -585;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Demandez à Kibler à propos du trésor ! SQUAWK !' WHERE `entry` = -584;
UPDATE `creature_ai_texts` SET `content_loc2` = 'SQUAWK !! *tousse* *tousse* Je dois arrêter de fumer !' WHERE `entry` = -583;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Bijou sait où les trésors sont cachés.' WHERE `entry` = -582;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s est maintenant armé !' WHERE `entry` = -581;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s sera armé dans 5 secondes !' WHERE `entry` = -580;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s sera armé dans 10 secondes !' WHERE `entry` = -579;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Meurs ! Meurs !' WHERE `entry` = -578;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Moi Grimlok, roi !' WHERE `entry` = -577;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Par la barbe de Thaurissan, tuez-les !' WHERE `entry` = -576;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Shaza-Kiel !' WHERE `entry` = -575;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Misérable nuisance !' WHERE `entry` = -574;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous n\'êtes... rien !' WHERE `entry` = -573;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous portez désormais... la marque.' WHERE `entry` = -572;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous mourrez dans d\'atroces souffrances.' WHERE `entry` = -571;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Implorez grâce ! Vos vies insignifiantes seront bientôt balayées !' WHERE `entry` = -570;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Aku\'mai est mort ! Je peux enfin quitter cet endroit maudit.' WHERE `entry` = -569;
UPDATE `creature_ai_texts` SET `content_loc2` = 'De la cendre... à la cendre...' WHERE `entry` = -568;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Dors...' WHERE `entry` = -567;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Qui ose interrompre ma méditation ?' WHERE `entry` = -566;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J\'avais l\'habitude de travailler pour le Grand Inquisiteur Isillien ! Votre conception de la douleur est un après-midi banal pour moi !' WHERE `entry` = -565;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Argh... La douleur... La douleur est presque aussi insupportable que les coups que j\'aie reçu à l\'école quand j\'étais un enfant.' WHERE `entry` = -564;
UPDATE `creature_ai_texts` SET `content_loc2` = 'ARGH ! Vous avez brûlé mon dernier jolie tabard !' WHERE `entry` = -563;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous frappez comme une fillette. Honnêtement. C\'est tout ce que vous savez faire ?' WHERE `entry` = -562;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tu peux me tuer, monstre. Je ne dirai RIEN !' WHERE `entry` = -561;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous serez bientôt suspendu à la potence, démon du Fléau !' WHERE `entry` = -560;
UPDATE `creature_ai_texts` SET `content_loc2` = 'NON ! S\'IL VOUS PLAÎT ! Il y a encore quelque chose que j\'avais oublié… Un messager va bientôt arriver… d\'Âtreval. Il…' WHERE `entry` = -559;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je ne sais presque rien d\'autre… Le grand général choisit ceux qui peuvent partir, et ceux qui doivent rester. Il n\'y a rien d\'autre… Il faut me croire !' WHERE `entry` = -558;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La Lumière qui nous guide. Ce mouvement a été lancé avant votre arrivée. Nous… nous… On ne fait qu\'obéir. Il doit en être ainsi.' WHERE `entry` = -557;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tout… Tout ce qu\'on nous a dit, c\'est que « l\'Aube cramoisie » est un éveil. Vous, vous voyez, la Lumière parle au grand général. C\'est la Lumière qui…' WHERE `entry` = -556;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vais tout vous dire ! ARRÊTEZ ! JE VOUS EN PRIE !' WHERE `entry` = -555;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Enfin, mon âme peut se reposer... Oh, cher Cerellean...' WHERE `entry` = -554;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Qui ose troubler le sanctuaire d\'Eldre\'Thalas ? Affrontez-moi, lâches !' WHERE `entry` = -553;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Salutations citoyen.' WHERE `entry` = -552;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s appelle à l’aide  !' WHERE `entry` = -551;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s entre dans une rage folle après avoir vu un ami tomber au combat !' WHERE `entry` = -550;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Gardes !' WHERE `entry` = -549;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Arrrhhh... Gardes !' WHERE `entry` = -548;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Formes de vie inconnues détectées... évaluation en cours...' WHERE `entry` = -547;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Cible perdue... reprise des activités de recherche Delta.' WHERE `entry` = -546;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Recherche de formes de vie... cible introuvable.' WHERE `entry` = -545;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s se concentre sur $N !' WHERE `entry` = -544;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Un de plus qui tombe !' WHERE `entry` = -543;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Déchaînez votre colère !' WHERE `entry` = -542;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous me servirez aussi !' WHERE `entry` = -541;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s MEURT DE FAIM !' WHERE `entry` = -540;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s commence à avoir vraiment faim !' WHERE `entry` = -539;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Activation des contre-mesures. Expulsion de l\'intrus.' WHERE `entry` = -538;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous avez été détecté. Vous allez être assimilé ou éliminé.' WHERE `entry` = -537;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Attention  ! Attention  ! Alerte intrus  !' WHERE `entry` = -536;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous êtes maudits, et nous sommes le remède.' WHERE `entry` = -535;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La chair est faible. Nous ferons de vous quelqu\'un de meilleur, de plus fort... de plus rapide.' WHERE `entry` = -534;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous sommes Mécagnome. Toute résistance est inutile.' WHERE `entry` = -533;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Arrêtez ! Stupides $C, nous ne pouvons pas vous laisser invoquer Myzrael !' WHERE `entry` = -532;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Prends ça ! Les Sèches-Moustaches l\'emporteront !' WHERE `entry` = -531;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Non ! Laisse-nous ! Nous ne devons pas faillir à notre tâche !' WHERE `entry` = -530;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tenez bon, mes frères. Et ne vous inquiétez pas ! La taille est de notre côté !' WHERE `entry` = -529;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Meurs ! Tu ne libéreras pas Myzrael !' WHERE `entry` = -528;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le Tout-Puissant va vous fracasser !' WHERE `entry` = -527;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s invoque un Vétéran Main-Noire en renfort !' WHERE `entry` = -526;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s invoque un Tisseur d\'effroi Main-noire pour qu\'il vienne l\'aider !' WHERE `entry` = -525;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s commence à invoquer un vétéran Main-noire !' WHERE `entry` = -524;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s commence à invoquer un Tisseur d\'effroi Main-noire !' WHERE `entry` = -523;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je me demande ce que Nesingwary me donnera en échange de votre peau  !' WHERE `entry` = -522;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ce soir, c\'est du veau !' WHERE `entry` = -521;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nesingwary va faire faillite si il conserve cette place ! Lane n\'a probablement aucune idée de ce qu\'il fait !' WHERE `entry` = -520;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Laisse tomber, petite bête !' WHERE `entry` = -519;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Seulement cinquante sabots de plus et à moi le nouveau flingue  !' WHERE `entry` = -518;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Impossible  ! Un heaume à tête de rhino pour le prix ridicule de trente têtes de rhinos  ? À ce prix-là, j’en prend deux  !' WHERE `entry` = -517;
UPDATE `creature_ai_texts` SET `content_loc2` = 'ÇA, c\'est du sport  !' WHERE `entry` = -516;
UPDATE `creature_ai_texts` SET `content_loc2` = 'TUE TUE TUE  !!!!!!!' WHERE `entry` = -515;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je suis sûr que l\'vieux Hemet trouvera quelque chose à faire avec vos os  !' WHERE `entry` = -514;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous cherchez à m\'assourdir ? C\'est pitoyable… Attendez… Quel est ce bruit ?' WHERE `entry` = -513;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Kada nu batteka, oht !' WHERE `entry` = -512;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Etu Magmothregar, cha !' WHERE `entry` = -511;
UPDATE `creature_ai_texts` SET `content_loc2` = 'KAGANISHU !' WHERE `entry` = -510;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Qui ose interrompre mon travail ?! Montrez-vous, lâche !' WHERE `entry` = -508;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Que signifie cette perturbation ?!' WHERE `entry` = -507;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Apportez-moi plus de prisonniers ! N\'ayez pas de repos avant qu\'Azeroth ne soit nettoyé de ses utilisateurs de magie imprudents !' WHERE `entry` = -506;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Remplissez-moi ces prisons de mages ! Malygos l\'exige !' WHERE `entry` = -505;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tout se passe comme prévu, Seigneur Lépervier. Je vous assure, ce n\'est qu\'une question de temps.' WHERE `entry` = -503;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J\'imagine que vous venez avec de bonnes nouvelles ?' WHERE `entry` = -502;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je commence à m\'ennuyer avec vous. Arrière !' WHERE `entry` = -501;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Dites à Impéréen que je vais envisager de cesser les hostilités. Mais d\'abord, Bouillonn doit cesser ses intrusions d\'élémentaires d\'eau sur mon domaine !' WHERE `entry` = -500;
UPDATE `creature_ai_texts` SET `content_loc2` = 'ARRÊTEZ !' WHERE `entry` = -499;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Qui ose ?' WHERE `entry` = -498;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous ne pouvez pas tous nous arrêter !' WHERE `entry` = -497;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Votre mort suivra bientôt...' WHERE `entry` = -496;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je suis le Maître des clés. Etes-vous le Portier ?' WHERE `entry` = -495;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La mort ne sera que le début de votre torture.' WHERE `entry` = -493;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Maintenant, hors de ma vue ! Vous serez sage de ne plus venir me voir.' WHERE `entry` = -489;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je me... soumets. Aussi longtemps que Simmer accepte de cesser de faire bouillir mon groupe, je suis d\'accord pour un armistice.' WHERE `entry` = -488;
UPDATE `creature_ai_texts` SET `content_loc2` = 'ATTENDEZ... ARRÊTEZ !' WHERE `entry` = -487;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le mojo de Sseratus est à nous. Maintenant, tout sera écrasé sous la puissance des Drakkari !' WHERE `entry` = -486;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Prenez une pleine gorgée mes frères !' WHERE `entry` = -485;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tuer ces envahisseurs qui osent souiller notre autel !' WHERE `entry` = -484;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vais détruire la Croisade d\'Argent ! Je vais écraser le Fléau !' WHERE `entry` = -483;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Finissez-les et ensuite nous irons vers le sud pour tuer leurs frères !' WHERE `entry` = -482;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ils osent nous attaquer ? Les imbéciles ! Ne savent-ils pas que nous sommes désormais tout-puissant ?!' WHERE `entry` = -481;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Grâce au pouvoir des dieux sauvages qui brûle dans nos veines, rien, pas même le roi-liche, ne peut se mettre en travers de notre chemin !' WHERE `entry` = -480;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vous vois, insecte ! Venez plus près.' WHERE `entry` = -479;
UPDATE `creature_ai_texts` SET `content_loc2` = 'NOOOOOOOOOooooooonnn......!' WHERE `entry` = -478;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mmmm, plus de mojo.' WHERE `entry` = -477;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Papa !' WHERE `entry` = -476;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Si Rhunok retrouve sa force, nous mourrons tous !' WHERE `entry` = -475;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Sale intrus de $R. MEURS !' WHERE `entry` = -474;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s est réduit en morceaux, mais continue à lutter.' WHERE `entry` = -473;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s voit sa force se réduire comme un rocher qui s\'effritte.' WHERE `entry` = -472;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s commence à craquer et se scinder.' WHERE `entry` = -471;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous avez ma parole que je vais trouver une utilité à votre corps après vous avoir tué, $R.' WHERE `entry` = -470;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous n\'arrêterez jamais les Réprouvés, $R. La Dame Noire va vous faire souffrir.' WHERE `entry` = -469;
UPDATE `creature_ai_texts` SET `content_loc2` = 'C\'est terminé.' WHERE `entry` = -468;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Krypta !' WHERE `entry` = -467;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Très… bien.' WHERE `entry` = -466;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Sale bête ! Obéis ! Tue-les ! Maintenant !' WHERE `entry` = -465;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous combattrons jusqu\'à la mort !' WHERE `entry` = -464;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vais finir ça rapidement...' WHERE `entry` = -463;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le Conseil des Bois de la Pénombre doit prendre des mesures. Le Mal s\'attarde autour de nous.' WHERE `entry` = -462;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Aber ? Est-ce que vous...? Oh... Je suis tellement affamé, Aber ! TELLEMENT AFFAMÉ !!!' WHERE `entry` = -461;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Attendez... vous n\'êtes pas mon mari. Mais il doit vous avoir envoyé. Et vous avez l\'air... délicieux !' WHERE `entry` = -460;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Les morts-vivants rampent partout sur notre terre. Où est l\'Armée d\'Hurlevent ?' WHERE `entry` = -459;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le peuple de Sombre-Comté attend plus du Conseil. Nous ne pouvons pas les laisser souffrir d\'avantage de cette colère funeste qui nous afflige.' WHERE `entry` = -458;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Notre cause tombe dans l\'oreille d\'un sourd, au-delà de l\'épaisseur des murs de pierre d\'Hurlevent.' WHERE `entry` = -457;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je crains que quelque chose de sombre n\'arrive.' WHERE `entry` = -456;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous avons besoin d\'être mieux représenté à Hurlevent. Nos maisons tombent à cause des morts-vivants.' WHERE `entry` = -455;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Les chamailleries continuelles ne nous mèneront nulle part. Nous avons besoin de prendre des décisions.' WHERE `entry` = -454;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Les nouvelles d\'Hurlevent ne sont pas de bon augure...' WHERE `entry` = -453;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La lumière semble nous avoir abandonné.' WHERE `entry` = -452;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Pourquoi la garde d\'Hurlevent ne vient-elle pas ?' WHERE `entry` = -451;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le labeur n\'a pas de rapport avec le passé, $N !' WHERE `entry` = -450;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Qui est ce misérable $R qui veut interférer avec ce qui s\'est passé ? Que la légende de Stalvan meurt avec vous !' WHERE `entry` = -449;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s laisse échapper un cri strident.' WHERE `entry` = -448;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le mage va tomber !' WHERE `entry` = -447;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous ne serons pas stoppés !' WHERE `entry` = -446;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La victoire ou la mort !' WHERE `entry` = -445;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous êtes à court de temps !' WHERE `entry` = -444;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La faille doit être protégée !' WHERE `entry` = -443;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vos efforts... sont vains.' WHERE `entry` = -442;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous n\'en avons pas fini !' WHERE `entry` = -441;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mort au Dernier Gardien !' WHERE `entry` = -440;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous ne faillirons pas !' WHERE `entry` = -439;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous sommes trahis !' WHERE `entry` = -438;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vais rester derrière et garder l\'épave. Dépêchez-vous ! Espérons que personne ne remarquera la fumée...' WHERE `entry` = -437;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Il semble que vous devez aller à Cabestan et dire à Krachevalve que je vais détruire le broyeur.' WHERE `entry` = -436;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Maintenant, il s\'agit d\'un exemple de ce qu\'il ne faut pas invoquer. Regarde, c\'est fragile et cassant. Un bon coup de masse enverra valdinguer des morceaux d\'os.' WHERE `entry` = -435;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J’veux voir la Tour des mages.' WHERE `entry` = -434;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Où on va ?' WHERE `entry` = -433;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Pourquoi on prend toujours le même chemin ?' WHERE `entry` = -432;
UPDATE `creature_ai_texts` SET `content_loc2` = 'C’est vrai ? Il y a vraiment des crocilisques dans les canaux ?' WHERE `entry` = -431;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J\'ai mal aux pieds.' WHERE `entry` = -430;
UPDATE `creature_ai_texts` SET `content_loc2` = 'On est arrivé ?' WHERE `entry` = -429;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Bien sûr je parle toute seule. Mais c\'est le seul moyen d\'avoir une conversation décente dans cette ville.' WHERE `entry` = -428;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Comme si, à mon grand âge, je n’avais pas mieux à faire que de porter des seaux d’eau.' WHERE `entry` = -427;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Où est l’eau, Emma  ? Va chercher l’eau, Emma  ! Si je m’en chargeais pas, y\'en aurait beaucoup qui n\'sauraient pas à quoi r\'semble l’eau.' WHERE `entry` = -426;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J’ai l’impression de faire une centaine de fois par jour ce trajet vers le puits pour aller chercher plus d’eau. Aucun respect pour leurs aînés, je vous dis.' WHERE `entry` = -425;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Jack et Jill me prennent pour une vieille mule ! Je passe ma journée à m\'occuper de l\'eau ici !' WHERE `entry` = -424;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J’ai l’impression de m’enraciner dans les pavés.' WHERE `entry` = -423;
UPDATE `creature_ai_texts` SET `content_loc2` = 'N\'oublie jamais que tu te trompes toujours plus que tu ne penses, gamin. Mets-en le double !' WHERE `entry` = -422;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Divisez la dose par deux la prochaine fois.' WHERE `entry` = -421;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Alors doublez la dose la prochaine fois !' WHERE `entry` = -420;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Monsieur, je pense que nous n\'étions pas loin du compte avec la poudre léthargique pour notre dernière recette.' WHERE `entry` = -419;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Monsieur, nos clients se plaignent d\'un excès d\'herbe mortelle dans nos poisons anesthésiants.' WHERE `entry` = -418;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Monsieur, nos clients se plaignent d\'un manque d\'angoisse de la vierge dans nos poisons mortels.' WHERE `entry` = -417;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tout à coup, ils étaient partout.' WHERE `entry` = -416;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Quelqu\'un a dû les aider.' WHERE `entry` = -415;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Si le capitaine me démasque, ce sera la fin pour moi.' WHERE `entry` = -414;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tout est de leur faute, stupide armée de l\'Alliance. Construire une de leurs tours juste derrière ma ferme.' WHERE `entry` = -413;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Quelques pièces pour un pauvre aveugle ?... Qu’est-ce que ça veut dire, je ne suis pas aveugle ?... JE NE SUIS PAS AVEUGLE ! JE VOIS !! C’est un miracle !' WHERE `entry` = -412;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je te paierai volontiers mardi pour avoir un bon steak aujourd’hui.' WHERE `entry` = -411;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Hmmm, celui-ci ressemble à quelque chose de mieux que le précédent. Prenez des notes... Ce n\'est pas ce genre de chose que vous voulez invoquer au coeur de la bataille.' WHERE `entry` = -410;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Prenez ces pièces et descendez-les dans le vaisseau !' WHERE `entry` = -409;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Quelqu\'un veut prendre une pause ? Et bien non ! Finissez votre travail malotrus !' WHERE `entry` = -408;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vais faire couler votre sang, $C !' WHERE `entry` = -407;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ne contrariez jamais un Sombrefer, $c.' WHERE `entry` = -406;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s semble beaucoup plus calme maintenant qu\'il a mangé les restes de $N.' WHERE `entry` = -405;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je ne peux pas vous autoriser à entrer dans le temple ! Je dois vous détruire pour votre propre bien !' WHERE `entry` = -404;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Faucon-dragon en approche en approche à l\'ouest ! Abattez-moi ce chasseur !' WHERE `entry` = -403;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Restez bien sur les démons. Aujourd\'hui, on s\'occupe pas de tuer les créatures du Fléau.' WHERE `entry` = -402;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ne laissez pas passer le faucon-dragon ! Ouvrez le feu !' WHERE `entry` = -401;
UPDATE `creature_ai_texts` SET `content_loc2` = 'C\'est tout ce que j\'avais à dire pour l\'instant. Restez sur le branle-bas, mes enfants.' WHERE `entry` = -400;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Inutile de le préciser, beaucoup d\'entre nous ne rentreront pas chez eux. Mais si vous appliquez votre entraînement et gardez la tête froide, vous serez un grand atout pour nous.' WHERE `entry` = -399;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Notre boulot est de dégager autant de cette chair à canon que possible, tout en aidant les spécialistes que les grands manitoux nous envoient.' WHERE `entry` = -398;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Là-haut, sur le plateau, lui et ses amis les démons essaient de rallumer le Puits de soleil et d\'ouvrir une faille pour ramener leur grand sachem, Kil\'Jaeden, en ce bas monde.' WHERE `entry` = -397;
UPDATE `creature_ai_texts` SET `content_loc2` = 'L\'île de Quel\'Danas a été envahie par les troupes du prince Kael\'thas Haut-soleil. Nos renseignements le donnaient pour mort. Nos renseignements se trompaient.' WHERE `entry` = -396;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Bonjour, jeunes recrues. Je suis le sergent instructeur Bahduum. Pour les quelques jours à venir, je serai chargé de vous orienter.' WHERE `entry` = -395;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Pour vos affectations précises, j\'attends les ordres. En attendant, restez ici et soyez prêts à partir d\'un instant à l\'autre !' WHERE `entry` = -394;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Les guerriers seront déployés pour tenir les points clés pendant que vous, les tireurs d\'élite, aurez pour mission de tenir les troupes volantes ennemies à distance.' WHERE `entry` = -393;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je peux vous assurer que, s\'il réussit, ce que ce monde subira sera bien pire que tout ce qu\'a jamais enduré l\'Outreterre. Alors faisons en sorte que ça n\'arrive pas.' WHERE `entry` = -392;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je sais, nous aussi nous pensions qu\'il était mort, mais ce n\'est pas le cas. Il essaie d\'utiliser le Puit de Soleil pour invoquer le maître de la Légion ardente, Kil\'Jaeden, en ce monde.' WHERE `entry` = -391;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La situation actuelle ressemble à peu près à ça : on tient ce qu\'on peut, pendant que des gens plus expérimentés et mieux équipés vont chercher Kael\'Thas.' WHERE `entry` = -390;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Bienvenue au Puit de Soleil. Malgré la température agréable et la belle vue, vous n\'êtes pas là pour les vacances, mesdames et messieurs !' WHERE `entry` = -389;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mesquine victoire !' WHERE `entry` = -388;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mesdames, si vous n\'avez pas de question, vous pouvez aller demander des instructions supplémentaires et vos affectations à vos chefs d\'unités. C\'est tout pour aujourd\'hui. Bonne chance !' WHERE `entry` = -387;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous sommes ici comme troupes de soutien pour les « aventuriers », c\'est leur petit nom, que les galonnés ont recrutés. Nous allons les aider à tenir les points clés de l\'île et baisser un peu la pression pour qu\'ils puissent faire leur boulot.' WHERE `entry` = -386;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Maintenant que ce point-là est éclairci, bienvenue sur l\'île de Quel\'Danas. Le Puit de Soleil se trouve sur le plateau au sud, et le prince Kael\'thas se terre sur la terrasse des Magistères, à l\'est.' WHERE `entry` = -385;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mais d\'abord, écoutez-moi, les sin\'dorei. Ici, on est pas là pour rigoler... Ça va vous changer de ce à quoi vous avez été habitué chez les Clairvoyants. Faites votre part du boulot, ou remontez sur le bateau !' WHERE `entry` = -384;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J\'ai déjà combattu aux côtés des draeneï à Skettis, et dans la vallée d\'Ombrelune. Mais maintenant, nous sommes en Azeroth. Et la situation a l\'air très mauvaise.' WHERE `entry` = -383;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Allons, calmez-vous. Nous avons beaucoup à faire et peu de temps pour le faire, mes amis.' WHERE `entry` = -382;
UPDATE `creature_ai_texts` SET `content_loc2` = 'GARDE-À-VOUS  !' WHERE `entry` = -381;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Dégagez, cet endroit est à nous !' WHERE `entry` = -380;
UPDATE `creature_ai_texts` SET `content_loc2` = 'À moi ! Vous ne prendrez pas cet endroit !' WHERE `entry` = -379;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Position de berserker ! Attaquez-les avec imprudence !' WHERE `entry` = -378;
UPDATE `creature_ai_texts` SET `content_loc2` = '[Orc] Gezzno il tov\'osh kaz kagg il Gesh\'zugas' WHERE `entry` = -377;
UPDATE `creature_ai_texts` SET `content_loc2` = '[Orc] Zaga ko thukad mog il kazum thok tar kagg il Gesh\'zugas' WHERE `entry` = -376;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Les yeux rougis |2 %s brillent tandis qu\'il allume sa dynamite et se met à caqueter comme un fou !' WHERE `entry` = -375;
UPDATE `creature_ai_texts` SET `content_loc2` = '[Nain] Thulmane um' WHERE `entry` = -374;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mourez au nom de Ragnaros !' WHERE `entry` = -373;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le Loch appartient à la Tribu Brisepierre maintenant, $N ! Mourez maintenant !' WHERE `entry` = -372;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mourez $R ! Ces terrains appartiennent à la Tribu Brisepierre !' WHERE `entry` = -371;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Un $C appelé $N ? Vous ferez un petit déjeuner parfait !' WHERE `entry` = -370;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Frappez-le !' WHERE `entry` = -369;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ce $R a l\'air bon à manger !' WHERE `entry` = -368;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Hein ? Quoi Dat ?' WHERE `entry` = -367;
UPDATE `creature_ai_texts` SET `content_loc2` = 'ARRRRRRR !' WHERE `entry` = -366;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je suis fatigué de ce non-sens ! Préparez vous à mourir !' WHERE `entry` = -365;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Héhéhé ! Je vous emporte avec moi !' WHERE `entry` = -364;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le Viaduc de Thandol va tomber pour Ragnaros. De même pour le Barrage de Formepierre !' WHERE `entry` = -363;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le Roi Magni Barbe-de-bronze est un imbécile et un charlatan !' WHERE `entry` = -362;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Raaar !!! Moi fracasser $R !' WHERE `entry` = -361;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Moi fracasser ! Vous mourir !' WHERE `entry` = -360;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vous écraserai !' WHERE `entry` = -359;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Il est temps de mourir, $c.' WHERE `entry` = -358;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Sentez le pouvoir des nains Sombrefer !' WHERE `entry` = -357;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Faible $C ! Vous n\'avez pas le niveau pour la Tribu Brisepierre !' WHERE `entry` = -356;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le seul bon $R est un $R mort !' WHERE `entry` = -355;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Yip ! Moi tuer !' WHERE `entry` = -354;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Moi pas fuir $c comme vous !' WHERE `entry` = -353;
UPDATE `creature_ai_texts` SET `content_loc2` = 'C\'était un Porto Pupellyverbos vieux de 200ans !' WHERE `entry` = -352;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ça a été gaspillé par des gens comme vous !' WHERE `entry` = -351;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Comment osez-vous déranger le dîner du Maître !' WHERE `entry` = -350;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Maintenant faites face à Orabus, misérable !' WHERE `entry` = -348;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le Timonier vient pour vous !' WHERE `entry` = -347;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s commence à invoquer des renforts !' WHERE `entry` = -346;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous vous sentez mieux, à ce que je vois.' WHERE `entry` = -345;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Buvez ceci, vous irez mieux.' WHERE `entry` = -344;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Laissez-moi vous aider.' WHERE `entry` = -343;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s appelle d’autres alliés à quitter les ténèbres.' WHERE `entry` = -342;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s surgit des ténèbres !' WHERE `entry` = -341;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s examine les informations sur l\'affiche "Recherché".' WHERE `entry` = -340;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s chuchote doucement d\'un ton respectueux.' WHERE `entry` = -339;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ahh, un autre puissant voyageur. Le coin peut être dangereux... vous voudrez les sorts les plus puissant à votre disposition. Je possède les meilleurs réactifs, communs ou exotiques. Venez et achetez - vous ne le regretterez pas !' WHERE `entry` = -338;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ici les créatures sont puissantes. Vous aurez besoin de beaucoup de munitions si vous souhaitez survivre. Vous êtes chanceux - je possède une bonne quantité de flèches, balles et armes de tir. Le prix est raisonnable considérant les circonstances.' WHERE `entry` = -337;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Cette guerre - et ne faites pas l’erreur de croire que ce n’est pas une guerre - ne va pas se gagner toute seule. Si nous ne faisons pas de notre mieux pour combattre, griffer, mordre et ruer pour chaque parcelle de cette terre brisée, tout est perdu.' WHERE `entry` = -336;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Combien de soldats devront mourir avant que nous commencions à faire un peu attention à ce qui se passe ici ?' WHERE `entry` = -335;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous pensez que les démons respectent les règles ? Ces bêtes sont plus sauvages que les orcs et plus rusées que les morts-vivants. N’essayez pas d’affronter la Légion selon les principes classiques de la guerre.' WHERE `entry` = -334;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je ne comprends pas ! Êtes-vous aveugle ? Ne pouvez-vous pas voir les démons frapper à nos portes ? Qui vais-je envoyé pour parler à vos amis chamans ? Choisis-les !' WHERE `entry` = -333;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Bron ! Hey Bron ! Hey Bron ! Frappe-moi !' WHERE `entry` = -332;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Non... c\'est pour les peureux. Frappe-moi avec ton marteau !' WHERE `entry` = -331;
UPDATE `creature_ai_texts` SET `content_loc2` = 'FAIS-LE, ESPÈCE DE JOUFFLU !' WHERE `entry` = -330;
UPDATE `creature_ai_texts` SET `content_loc2` = '... C\'ÉTAIT GÉNIAL !' WHERE `entry` = -329;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s bat des cils, une expression perplexe passant sur son visage.' WHERE `entry` = -328;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Quoi, avec mes poings ?' WHERE `entry` = -327;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je... ne suis pas certain que ce soit une bonne idée, \'Moke. Tu pourrais te blesser...' WHERE `entry` = -326;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Euh… Momoke ?' WHERE `entry` = -325;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Il est temps de tout casser !' WHERE `entry` = -324;
UPDATE `creature_ai_texts` SET `content_loc2` = 'So ju weh siame is fus nehjo skam worl Uptfeel' WHERE `entry` = -323;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Dim wha Siame cyaa fi so yudo' WHERE `entry` = -322;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Iman m t\'ief fu Fus\'obeah italaf' WHERE `entry` = -321;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Les sables vous consument !' WHERE `entry` = -320;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je devrais peut-être recueillir quelques autres agents et les commander suite à ce changement ?' WHERE `entry` = -319;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La dernière fois que quelqu\'un est allé essayer de recueillir la prime sur Netherlock, il nous est retourné écrasé comme une cape d\'aventurier téméraire !' WHERE `entry` = -318;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Avec une récompense comme ça, comment pourraient-ils refuser ?' WHERE `entry` = -317;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Si je vois un paysan lâche par ici... je le charge dans une catapulte et je l\'envoie sur le Temple Noir !' WHERE `entry` = -316;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Quand vous voudrez vous reposer, paysan, le cimetière est juste là...' WHERE `entry` = -315;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Satanés ogres. Quelqu\'un nous sauvera t\'il de ces sauvages ? C\'est le cinquième enlèvement en si peu de jours.' WHERE `entry` = -314;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ceci est la meilleure récompense que nous pouvons offrir. Espérons que quelqu\'un acceptera la mission...' WHERE `entry` = -313;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Comment s\'y prend-il ?' WHERE `entry` = -312;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Celui-ci est légèrement mieux que le dernier. Pourtant, il souffre toujours de la même fragilité osseuse que les autres. Lorsque vous en invoquez un, vous êtes sur la bonne voie.' WHERE `entry` = -311;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je veux être exactement comme ce combattant !' WHERE `entry` = -310;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Il est tellement bien discipliné !' WHERE `entry` = -309;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vaincra-t-il ? Le peut-il ?' WHERE `entry` = -308;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Wow ! Regardez ces muscles !' WHERE `entry` = -307;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Priez vos dieux, chaman. Peut-être vous aideront-ils. La Horde par contre, ne le peut pas...' WHERE `entry` = -306;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous n\'avez pas d\'yeux ? N\'avez-vous pas vu les démons à nos portes ? Je n\'ai pas de soldat à vous passer !' WHERE `entry` = -305;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Que me voulez-vous, chaman ?' WHERE `entry` = -304;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Oui, nous avons des problèmes. Je crois que c\'est clair comme de l\'eau de roche. La question est : que ferez vous à ce propos ?' WHERE `entry` = -303;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le chef a mis la tête d\'Arazzius à prix ! Et maintenant, ce bon à rien de démon est l\'ennemi numéro un.' WHERE `entry` = -302;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mais comment est-ce possible, chef ? Je croyais que la malédiction était levée...' WHERE `entry` = -301;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous voulez dire...' WHERE `entry` = -300;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Quels sortes d\'orcs, chef ?' WHERE `entry` = -299;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J\'ai vu des gnomes travailler plus fort que vous, paysan ! Des fillettes gnomes - avec des queues de cheval ! BOUGEZ-VOUS !' WHERE `entry` = -298;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Votre nourriture est prête. Venez la chercher...' WHERE `entry` = -297;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Et si j\'entends que vous êtes encore allés vous plaindre à Nazgrel, ce sera un de vous dont je m\'occuperai la prochaine fois...' WHERE `entry` = -296;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Si mon estomac ne menaçait pas de sortir de mon corps et de se sauver pour manger ce que nous donnons aux prisonniers, je pourrai être insulté par cette... nourriture.' WHERE `entry` = -295;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Est-ce que je détecte un soupçon de cannelle ? Ou est-ce de la noix de muscade ? Peu importe ce que c\'est, une chose est sûre... personne ne cuisine comme vous !' WHERE `entry` = -294;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Donc nous y étions - moi et le bataillon, faisant une ronde de routine. Nous avons envoyé les éclaireurs pour vérifier au cas où il y aurait du danger.' WHERE `entry` = -293;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Certainement, il est revenu en courant, parlant de quelques orcs sur le chemin. Ils ne nous avaient pas encore vu, donc nous avons pensé à aller les rencontrer.' WHERE `entry` = -292;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Gros bâtards rouges ! Plus gros que n\'importe quel orc que j\'ai jamais vu. Des muscles jusqu\'ici...' WHERE `entry` = -291;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Gangr\'orc...' WHERE `entry` = -290;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J\'sais pas, *grogne*. Je - ne - sais - juste - pas...' WHERE `entry` = -289;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mais ce n\'est pas le pire. Avant d\'avoir pu nous rassembler, un groupe nous a repéré et nous a attaqué.' WHERE `entry` = -288;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J\'ai perdu plusieurs de mes meilleurs soldats ce jour là...' WHERE `entry` = -287;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s approuve.' WHERE `entry` = -286;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Par les Naaru, qu\'il en soit ainsi.' WHERE `entry` = -285;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Donnez-nous la tolérance pour nos visiteurs elfiques.' WHERE `entry` = -284;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Continue de bénir ceci, nos anciennes demeures, nous vous supplions.' WHERE `entry` = -283;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Bénissez et protégez-les. Donnez-leur la victoire contre ceux qui nous veulent du mal...' WHERE `entry` = -282;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Dans notre guerre contre l\'ombre, nous avons envoyé nos enfants.' WHERE `entry` = -281;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Lumière que nous embrassons, nous te sollicitons...' WHERE `entry` = -280;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mes amis, joignez-moi en prière pour la Lumière.' WHERE `entry` = -279;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Une noble requête. Ce sera un honneur, Erothem.' WHERE `entry` = -278;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Bien sûr mon ami. Comment puis-je vous servir ?' WHERE `entry` = -277;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Qu\'il en soit ainsi.' WHERE `entry` = -276;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous venons d\'envoyer un autre équipe sans expérience à Nagrand. Ferez-vous une prière pour eux ?' WHERE `entry` = -275;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Anchorite Nindumen, j\'ai une requête pour vous.' WHERE `entry` = -274;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Qu\'il en soit ainsi.' WHERE `entry` = -273;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J\'ai des muffins ici-même. Venez par ici !' WHERE `entry` = -272;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Oui, oui, Je suis l\'homme aux muffins. Vous savez pourquoi ? Parce que je vends des muffins, voilà pourquoi !' WHERE `entry` = -271;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ouais, ça c\'est le bon endroit. Muffins à vendre ! Achetez vos muffins frais ici !' WHERE `entry` = -270;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Rien de telle qu\'une bonne boisson pour faire glisser un de mes magnifiques muffins.' WHERE `entry` = -269;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Grok fâché si va pas à Blade\'s Edge et parler à Mog\'dorg !' WHERE `entry` = -268;
UPDATE `creature_ai_texts` SET `content_loc2` = 'MARCHANDE DE FRUITS  ! Votre chariot est ENCORE dans notre chemin  ! Mais c\'en est fini de vous  ! Vous avez un nouveau concurrent pour la vente de fruits  !' WHERE `entry` = -267;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Grok a faim. Fruit a l\'air bon.' WHERE `entry` = -266;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Z\'avez l\'air d\'vous languir. L\'être cher qui vous délaisse, c\'est ça  ? Pas d\'soucis, pas d\'soucis. Vous m\'prenez ce médaillon, vous l\'portez quand vous l\'revoyez, et vous aurez plus une minute à vous, mon grand  !' WHERE `entry` = -265;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je sens que la guerre approche rapidement. Le vendeur de fruits a décidé d\'aider un ogre. Je devrais envisager d\'aider aussi.' WHERE `entry` = -264;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Quel est le propos des cris de ce pauvre orc ? Quelqu\'un devrait aller voir de quoi il s\'agit.' WHERE `entry` = -263;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Z\'avez l\'air fatigué, $c. J\'dois avoir quequ\'chose pour vous. Ces amulettes, elles peuvent vous aider à sauter par-d\'sus les obstacles et à nager dans les rivières comme si vous y étiez né. Elles énergétisent la nourriture que vous mangez, pour que vos blessures se referment à vue d\'œil  !' WHERE `entry` = -262;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Clan Flèchelame combattre sans honneur. Avoir gronns pour aider. Vous allez dans les Tranchantes, vous parlez à Mog\'dorg le Ratatiné. Vous tuez les gronns.' WHERE `entry` = -261;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mog\'dorg le Sage dit Grok va à ville, trouve aide. Grok va.' WHERE `entry` = -260;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Grok besoin aide. Pourquoi personne aide ?' WHERE `entry` = -259;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Hé hé, $r  ! J\'ai exactement ce qu\'il vous faut. Vous avez déjà vu un tikbalang  ? Sales bêtes. Elles vous emportent et…et c\'est pour ça qu\'il vous faut une protection contre les tikbalangs  ! Garantie pour les chasser très, très loin  !' WHERE `entry` = -258;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Venez voir par ici, $c  ! J\'ai un truc pour vous. Pile c\'qu\'il vous faut. C\'est du savon, voyez... et c\'est au bout d\'une corde  ! Rien de personnel, mon pote, mais ça commence à fouetter un peu, si vous voyez c\'que j\'veux dire.' WHERE `entry` = -257;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Si personne aide, Grok va taper  !' WHERE `entry` = -256;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J\'aurais juré que j\'avais plus de pommes que ça. Grok  !' WHERE `entry` = -255;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Alléchantes amulettes  ! Renversantes raretés  ! Même les joailliers de la dernière mode ne savent rien des nouvelles méthodes ancestrales de maître Eskrokar  ! Améliorez-vous grâce à ces talismans magiques à prix bradés  !' WHERE `entry` = -254;
UPDATE `creature_ai_texts` SET `content_loc2` = 'L\'coin est dangereux, pas vrai  ? Savez c\'qu\'il vous faut  ? Une protection. J\'peux vous aider à défier la mort en personne  ! Portez cette follepierre autour d\'votre cou, voyez, et vous pourrez revenir si vous vous faites expédier dans le monde des esprits  ! Une petite balade jusqu\'à vot\' cadavre, et vous revoilà, frais et dispos   !' WHERE `entry` = -253;
UPDATE `creature_ai_texts` SET `content_loc2` = 'V\'nez là, $r. Vous voulez quand même pas risquer vot\' vie dans un donjon, sérieusement  ? Faire un boulot dégueulasse, et pour quoi  ? Une babiole sans valeur  ? Pfff, c\'qu\'il vous faut vraiment, c\'est une de mes amulettes. Leur fonctionnement est garanti  !' WHERE `entry` = -252;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s s\'évanouit.' WHERE `entry` = -251;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Apprendre à lire n\'est pas une tâche aisée. Un toast, hein ?' WHERE `entry` = -250;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Expédiez cela !' WHERE `entry` = -249;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je n\'aurai jamais imaginé qu\'il se serait transformé en huile de mana ! Il va y avoir beaucoup de demandes pour ça, en dehors de celle de Grek naturellement !' WHERE `entry` = -248;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Grek prend à boire' WHERE `entry` = -247;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Cette huile n\'est pas bonne pour Grek ! À quoi Grek vous ressemble, un certain faible dans des robes ?' WHERE `entry` = -246;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Grek essai !' WHERE `entry` = -245;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Quelqu\'un vient lire cette affiche de recherche à Grek. Grek ne sait pas lire.' WHERE `entry` = -244;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous mourrez pour votre orgueil, druide !' WHERE `entry` = -243;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous osez déranger les disciples loyaux du Corbeau ?' WHERE `entry` = -242;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous mourrez pour votre orgueil, druide !' WHERE `entry` = -241;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous osez déranger les disciples loyaux du Corbeau ?' WHERE `entry` = -240;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le temps du Corbeau est la nuit, mais le vôtre finira ici !' WHERE `entry` = -239;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Imbécile ! L\'essence du faucon ne sera jamais la vôtre !' WHERE `entry` = -238;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s cible $N.' WHERE `entry` = -237;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s expose ses crocs et menace ceux qui se trouvent autour d\'elle.' WHERE `entry` = -236;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s fait voler sa chair en lambeaux en entrant dans une colère surnaturelle !' WHERE `entry` = -235;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Un vent violent enveloppe Vakkiz qui se tortille vers vous d\'un air menaçant.' WHERE `entry` = -234;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tellement à faire, tellement à faire ! Où le temps va-t-il ?' WHERE `entry` = -233;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La Fraternité ne sera pas gênée par des insectes.' WHERE `entry` = -232;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vous découperai !' WHERE `entry` = -231;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous serez mort bientôt !' WHERE `entry` = -230;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tuer vous être facile.' WHERE `entry` = -229;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Moi transformer vous en mojo !' WHERE `entry` = -228;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Que la terre et le ciel s\'embrasent !' WHERE `entry` = -227;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Que le feu pleuve du ciel !' WHERE `entry` = -226;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Faites de beaux rêves...' WHERE `entry` = -225;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous semblez fatigué…' WHERE `entry` = -224;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La peste soit sur vous !' WHERE `entry` = -223;
UPDATE `creature_ai_texts` SET `content_loc2` = 'L\'essaim est affamé.' WHERE `entry` = -222;
UPDATE `creature_ai_texts` SET `content_loc2` = 'L\'heure… tourne… encore.' WHERE `entry` = -221;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Dommage, pas le temps de vous faire mourir à petit feu !' WHERE `entry` = -220;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je veux vous entendre crier !' WHERE `entry` = -219;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tout espoir est perdu !' WHERE `entry` = -218;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous défendez un monde condamné ! Fuyez si vous voulez avoir une chance de faire durer vos vies pathétiques !' WHERE `entry` = -217;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tous vos efforts ont été vains, car l\'assèchement de l\'Arbre-Monde a déjà commencé. Bientôt le coeur de ce monde aura cessé de battre.' WHERE `entry` = -216;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Détruire !' WHERE `entry` = -215;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tuer !' WHERE `entry` = -214;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Écraser !' WHERE `entry` = -213;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Aaaahhhhhh !' WHERE `entry` = -212;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mourez au nom d\'Edwin Cleef !' WHERE `entry` = -211;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vais vous envoyer dans votre tombe, faible $C !' WHERE `entry` = -210;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J\'ai un message spécial pour $N. Et il dit que vous devez mourir !' WHERE `entry` = -209;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous n’auriez pas une ou deux pièces ?' WHERE `entry` = -208;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Un coup de main à un pauvre malheureux ?' WHERE `entry` = -207;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je ferai reluire votre armure pour une simple pièce de cuivre.' WHERE `entry` = -206;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Pain frais, tout juste sorti du four !' WHERE `entry` = -205;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Pain frais  !' WHERE `entry` = -204;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ma reth bromo zoln kilagrin dra ma zoern tu ko fraht ka tadrom Ma krin drinor zaln dirnor Ma krin kan aasrugel korsul' WHERE `entry` = -203;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Votre tête fera un trophée parfait , $R.' WHERE `entry` = -202;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mes serres déchiquetteront votre corps chétif, $R.' WHERE `entry` = -201;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous serez une proie facile, $C.' WHERE `entry` = -200;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Souffre méprisable insecte !' WHERE `entry` = -199;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous n\'avez rien à faire ici ! Tuez-les !' WHERE `entry` = -198;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous pouvons le rendre meilleur, plus fort, plus rapide. Nous disposons de la technologie. Nous avons la magie.' WHERE `entry` = -197;
UPDATE `creature_ai_texts` SET `content_loc2` = 'C\'est dangeureux ici, maître. Mais j\'aiderai à monter la garde.' WHERE `entry` = -196;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Brzt... click... whir...' WHERE `entry` = -195;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Un jour, je serai un vrai petit garçon.' WHERE `entry` = -194;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Bidulotron... ok. Doothingies... ok. Wizzers... ok.' WHERE `entry` = -193;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Il peut faire vraiment très chaud ici dans les Terres ingrates. Mais au moins, c\'est une chaleur sèche.' WHERE `entry` = -192;
UPDATE `creature_ai_texts` SET `content_loc2` = '... et restez mort ! Toujours prêt à aider !' WHERE `entry` = -191;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Des explosions ! ENCORE des explosions ! Je veux plus d\'explosions !' WHERE `entry` = -190;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mes machines, c\'est l\'avenir ! Elles vous détruiront tous !' WHERE `entry` = -189;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Usurpateurs ! Gnomeregan est à moi !' WHERE `entry` = -188;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s appelle ses worgs.' WHERE `entry` = -187;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La vie est ici !' WHERE `entry` = -186;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Avouez et nous vous libérerons.' WHERE `entry` = -185;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tu parleras. Tu ferais mieux de tout déballer maintenant.' WHERE `entry` = -184;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Quoi ? Oh non. Je ne me soucie pas de ce que vous devez dire. J\'apprécie juste d\'infliger la douleur.' WHERE `entry` = -183;
UPDATE `creature_ai_texts` SET `content_loc2` = 'À moi ! À moi ! À moi ! Kadenaz est le maître de ce domaine ! Vous ne révélerez jamais ma présence !' WHERE `entry` = -182;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous sommes la vraie Horde !' WHERE `entry` = -181;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mes animaux de compagnie ont faim et ils dîneront sur votre chair !' WHERE `entry` = -180;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Des intrus ! Retenez-les, que je puisse libérer les chiens de guerre !' WHERE `entry` = -179;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Les cigares ? Vous allez devoir me refroidir pour les avoir... Argh !' WHERE `entry` = -178;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vais porter votre peau comme une veste de smoking !' WHERE `entry` = -177;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je commence sérieusement à m\'échauffer !' WHERE `entry` = -176;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous êtes plus coriaces que je ne le pensais. Je vais devoir improviser.' WHERE `entry` = -175;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous sommes attaqués ! Repoussez les envahisseurs !' WHERE `entry` = -174;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La Confrérie vaincra !' WHERE `entry` = -173;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Idiots ! Notre cause est juste !' WHERE `entry` = -172;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Chiens !' WHERE `entry` = -171;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Et ne vous relevez pas !' WHERE `entry` = -170;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nul ne peut défier la Confrérie !' WHERE `entry` = -169;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Qui ose me déranger ? Meurs $N !' WHERE `entry` = -168;
UPDATE `creature_ai_texts` SET `content_loc2` = 'MEURS !!!' WHERE `entry` = -167;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Bientôt, le Fléau régnera sur le monde !' WHERE `entry` = -166;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous nous répandrons partout !' WHERE `entry` = -165;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous réduirons les hurans en esclavage !' WHERE `entry` = -164;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tuez-les, mes frères ! Pour le Fléau !' WHERE `entry` = -163;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mmm... j\'adore ma délicieuse Bière brune d’Austrivage.' WHERE `entry` = -162;
UPDATE `creature_ai_texts` SET `content_loc2` = '$gUn:Une:r; $r $gvivant:vivante;... $gil:elle; sera bientôt $gmort:morte; comme moi.' WHERE `entry` = -161;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ce monde nous APPARTIENT !' WHERE `entry` = -160;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Lok\'tar Illidari !' WHERE `entry` = -159;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Pour Kargath ! Pour la Victoire !' WHERE `entry` = -158;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Lok narash !' WHERE `entry` = -157;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le sang est notre pouvoir !' WHERE `entry` = -156;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s commence à armer la bombe de proximité !' WHERE `entry` = -155;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Illidan règne !' WHERE `entry` = -154;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La force de %s décline.' WHERE `entry` = -153;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s grandit à la vue |2 $N !' WHERE `entry` = -152;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s devient instable et commence à se désintégrer !' WHERE `entry` = -149;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Youpi ! Merci !' WHERE `entry` = -148;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Envahisseurs ! Sonnez l\'alarme !' WHERE `entry` = -141;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Les rouleaux de la mort... Vous écraserons.' WHERE `entry` = -140;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Viens à moi mon frère !' WHERE `entry` = -139;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous me faites perdre mon temps. Rien d\'autre !' WHERE `entry` = -138;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Zêtes nuls !' WHERE `entry` = -137;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Arrêtez de pleurnicher !' WHERE `entry` = -136;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mangez, mes frères !' WHERE `entry` = -135;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mon esprit... vous pouvez pas... le tuer !' WHERE `entry` = -134;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Moi j\'suis le prédateur ! Vous êtes la proie...' WHERE `entry` = -133;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous avez gagné cette bataille, mais pas… la… guerre.' WHERE `entry` = -132;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Victoire à la Légion !' WHERE `entry` = -131;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Toute vie doit périr !' WHERE `entry` = -130;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Des cendres aux cendres, de poussières à poussières.' WHERE `entry` = -129;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tombez et pourrissez !' WHERE `entry` = -128;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Il fera bien plus froid dans vos tombes.' WHERE `entry` = -127;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Succombez au frisson glacé... de la mort !' WHERE `entry` = -126;
UPDATE `creature_ai_texts` SET `content_loc2` = 'L\'ultime invasion de la Légion a commencé ! Une fois de plus, l\'asservissement de ce monde est à notre portée. Ne faites pas de quartier !' WHERE `entry` = -125;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Insolence !' WHERE `entry` = -124;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je suis le roi serpent ! Je peux faire n\'importe quoi.' WHERE `entry` = -123;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nul ne viendra te sauver !' WHERE `entry` = -122;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Votre temps viendra bientôt…' WHERE `entry` = -121;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Inutile de lutter.' WHERE `entry` = -120;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Voilà juste un avant-goût... de ce qui vous attend…' WHERE `entry` = -119;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Reesh, hokta !' WHERE `entry` = -118;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Abandonnez tout espoir ! La Légion est revenue finir ce qui avait été commencé il y a si longtemps. Cette fois, il n\'y aura pas d\'échappatoire !' WHERE `entry` = -117;
UPDATE `creature_ai_texts` SET `content_loc2` = 'À quoi sert cette violence ? Ce qui est fait est fait. J\'ai laissé tomber mon peuple.' WHERE `entry` = -116;
UPDATE `creature_ai_texts` SET `content_loc2` = 'N\'avez-vous pas fait assez de mal ? Devez-vous également perturber mon sommeil ?' WHERE `entry` = -115;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je ne supporte plus la douleur. Je dois trouver une nouvelle source.' WHERE `entry` = -114;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Plus, plus, plus ! Je dois bientôt me nourrir.' WHERE `entry` = -113;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Votre monde est maintenant à nous.' WHERE `entry` = -112;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s éclate, tapissant la zone de résidus d\'arcanes !' WHERE `entry` = -111;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Courage ! Vos amis ne pleureront pas longtemps votre trépas !' WHERE `entry` = -110;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Respectez la loi !' WHERE `entry` = -109;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Servez la confiance du peuple !' WHERE `entry` = -108;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Protégez les innocents !' WHERE `entry` = -107;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s est prise de frénésie !' WHERE `entry` = -106;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vos os se casseront sous ma botte, $R !' WHERE `entry` = -105;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Cette terre appartient aux Nains Sombrefer. Prépare toi à voir la vie après la mort, $C !' WHERE `entry` = -104;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Cerveaux...' WHERE `entry` = -103;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Longue vie aux Gueules-de-Dragons ! Meurs pauvre $R !' WHERE `entry` = -102;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Pour les Gueule-de-dragon !' WHERE `entry` = -101;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s pousse un cri strident pour appeler à l’aide !' WHERE `entry` = -100;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous ne réveillerez jamais le rêveur !' WHERE `entry` = -99;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je… le… mérite...' WHERE `entry` = -98;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous n\'auriez pas dû venir.' WHERE `entry` = -97;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Il fallait le faire.' WHERE `entry` = -96;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous l’avez bien cherché !' WHERE `entry` = -95;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ne me forcez pas à vous tuer !' WHERE `entry` = -94;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le travail doit continuer.' WHERE `entry` = -93;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ne dites pas que je ne vous avais pas prévenu !' WHERE `entry` = -92;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous croyez que vous pouvez me faire mal, hum ? Vous croyez que j\'ai peur de vous ?' WHERE `entry` = -91;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Allez-y donnez moi ce que vous avez de mieux. Je peux encaisser !' WHERE `entry` = -90;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Brutes !' WHERE `entry` = -89;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Qu\'est ce que je suis bon ! J\'me la pète mais c\'est la fête !' WHERE `entry` = -88;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Dégagez tant que vous le pouvez.' WHERE `entry` = -87;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vous prédis une mort douloureuse.' WHERE `entry` = -86;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Et si ma division est bien posée, je crois que vous êtes mort.' WHERE `entry` = -85;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mesurer deux fois, couper une fois !' WHERE `entry` = -84;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Voilà... impondérable.' WHERE `entry` = -83;
UPDATE `creature_ai_texts` SET `content_loc2` = 'C\'était la seule issue logique.' WHERE `entry` = -82;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Votre stratégie était imparfaite.' WHERE `entry` = -81;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vous taillerai en pièces !' WHERE `entry` = -80;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Maintenant je suis vraiment... énervée...' WHERE `entry` = -79;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ahh... Exactement ce que j\'attendais.' WHERE `entry` = -78;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ahh... C\'est beaucoup mieux.' WHERE `entry` = -77;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Maintenant je suis vraiment... en colère...' WHERE `entry` = -76;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous n\'avez pas choisi le bon adversaire.' WHERE `entry` = -75;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Complètement inapte. Ça me rappelle fortement quelqu\'un.' WHERE `entry` = -74;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Il est imprudent de me mettre en colère.' WHERE `entry` = -73;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous allez réussir à vous damner vous même !' WHERE `entry` = -72;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Partez tant qu\'il est encore temps !' WHERE `entry` = -71;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Cela... ne changera rien. La damnation éternelle vous attend !' WHERE `entry` = -70;
UPDATE `creature_ai_texts` SET `content_loc2` = 'D\'autres prendront ma place !' WHERE `entry` = -69;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le même sort attend tous ceux qui veulent voler le maître' WHERE `entry` = -68;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La mort est bien trop miséricordieuse à votre goût.' WHERE `entry` = -67;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Il est temps de partir...' WHERE `entry` = -66;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Libre... au moins' WHERE `entry` = -65;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Est-ce vraiment passé ?' WHERE `entry` = -64;
UPDATE `creature_ai_texts` SET `content_loc2` = 'C\'est tout... revenez me voir.' WHERE `entry` = -63;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Oui... Je crois que je me rappelle maintenant...' WHERE `entry` = -62;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J\'ai loupé le spectacle !' WHERE `entry` = -61;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ils se sont endormis après. Moi, je me suis endormi pendant...' WHERE `entry` = -60;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Oui... Je crois que je me rappelle maintenant...' WHERE `entry` = -59;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Il a demandé si l\'imp pouvait nous rejoindre... vous le croyez ? Généralement, ce n\'est pas plus mal...' WHERE `entry` = -58;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Et j\'ai dis, "Ok, mais cela vous coûtera un supplément."' WHERE `entry` = -57;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Cinq secondes ! Je ne plaisante pas !' WHERE `entry` = -56;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous serez puni !' WHERE `entry` = -55;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous... allez... payer...' WHERE `entry` = -54;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Que se passe-t-il ?' WHERE `entry` = -53;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Où suis-je ? Quoi ?' WHERE `entry` = -52;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le destin s\'est retourné contre moi !' WHERE `entry` = -51;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ce n\'est... pas juste...' WHERE `entry` = -50;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Attendez... non ! Non !' WHERE `entry` = -49;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s vous a repéré !' WHERE `entry` = -48;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s essaie de s\'enfuir dans un moment de panique  !' WHERE `entry` = -47;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s est prise de frénésie !' WHERE `entry` = -46;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le maître... sera en colère...' WHERE `entry` = -45;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je suis fini !' WHERE `entry` = -44;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Non !' WHERE `entry` = -43;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Il est temps de nous rejoindre, $c.' WHERE `entry` = -42;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Que vont devenir...' WHERE `entry` = -41;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Est-ce la fin ?' WHERE `entry` = -40;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Gardes à moi ! Fauchez ces intrus !' WHERE `entry` = -39;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Band\'or shorel\'aran !' WHERE `entry` = -38;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous n\'avez plus à faire à un sous-fifre.' WHERE `entry` = -37;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je n\'ai pas encore... commencé...' WHERE `entry` = -36;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Oh ! Cessez ces gémissements.' WHERE `entry` = -35;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Avancez-vous ! Je vais faire en sorte que vous receviez un bon accueil.' WHERE `entry` = -34;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le vide... m\'appelle.' WHERE `entry` = -33;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Plus... de... vie.' WHERE `entry` = -32;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Cette enveloppe... est vide.' WHERE `entry` = -31;
UPDATE `creature_ai_texts` SET `content_loc2` = 'L\'ombre... vous engloutira.' WHERE `entry` = -30;
UPDATE `creature_ai_texts` SET `content_loc2` = 'De l\'énergie... à consommer.' WHERE `entry` = -29;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous venez tuer Dalliah ? Je peux regarder ?' WHERE `entry` = -28;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Enfin, de quoi évacuer ma frustration !' WHERE `entry` = -27;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ça fait du bien par où ça passe.' WHERE `entry` = -26;
UPDATE `creature_ai_texts` SET `content_loc2` = 'C\'était... la seule issue... pour moi.' WHERE `entry` = -25;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Défendez-vous, même si ça ne sert à rien...' WHERE `entry` = -24;
UPDATE `creature_ai_texts` SET `content_loc2` = 'En garde !' WHERE `entry` = -23;
UPDATE `creature_ai_texts` SET `content_loc2` = 'VanCleef paie bien pour vos têtes !' WHERE `entry` = -22;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Il faut préserver... les spécimens.' WHERE `entry` = -21;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Votre cycle de vie est maintenant terminé !' WHERE `entry` = -20;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Endorel aluminor !' WHERE `entry` = -19;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La nature se plie à ma volonté !' WHERE `entry` = -18;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Que faites-vous ? Ce sont des spécimens très fragiles !' WHERE `entry` = -17;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous n\'irez pas loin...' WHERE `entry` = -16;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Cela me peine à dire... mais je vous avais prévenu !' WHERE `entry` = -15;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ta vie m\'appartiens !' WHERE `entry` = -14;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous cherchiez une récompense, hein ? Vous avez trouvé la mort !' WHERE `entry` = -13;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je me délecte de ta douleur...' WHERE `entry` = -12;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vais vous réduire en cendre !' WHERE `entry` = -11;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Hurlez sous mon déluge de flamme !' WHERE `entry` = -10;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Quelle est cette nuisance ? Vous allez mourir !' WHERE `entry` = -9;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Yiieeeee ! Moi courir !' WHERE `entry` = -8;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous pas prendre bougie !' WHERE `entry` = -7;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Grrrr... de la viande fraîche !' WHERE `entry` = -6;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Plus d\'os à ronger...' WHERE `entry` = -5;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Sentez le pouvoir de la Confrérie !' WHERE `entry` = -4;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ah, une occasion d\'utiliser cette lame fraîchement aiguisée.' WHERE `entry` = -3;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La Confrérie ne tolérera pas vos actions.' WHERE `entry` = -2;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vois que ces imbéciles de l\'Abbaye ont envoyé de la viande fraîche pour nous.' WHERE `entry` = -1;
